---
  - hosts: database
    tasks:
      - name: 'Instala pacotes de dependencia do sistema operacional'
        apt:
          name: '{{ item }}'
          state: latest
        become: yes
        with_items:
          - mysql-server-5.6
          - python-mysqldb
      
      - name: 'Cria o banco MySql'
        mysql_db:
          name: "{{ wp_db_name }}"
          login_user: root
          state: present

      - name: 'Cria o usuário do MySql'
        mysql_user:
          login_user: root
          name: "{{ wp_username }}"
          password: "{{ wp_user_password }}"
          priv: "{{ wp_db_name }}.*:ALL"
          state: present
          host: "{{ item }}"
        with_items:
          - 'localhost'
          - '127.0.0.1'
          - "{{ wp_host_ip }}"

  - hosts: wordpress
    handlers:
      - name: Reiniciar Apache
        service:
          name: apache2
          state: restarted
        become: yes 
    tasks:
      - name: 'Instala pacotes de dependencia do sistema operacional'
        apt:
          name:
            - php5
            - apache2
            - libapache2-mod-php5
            - php5-gd
            - libssh2-php
            - php5-mcrypt
            - python-mysqldb
          state: latest
        become: yes

      - name: 'Baixa o arquivo de instalação do wordpress'
        get_url:
          url: 'https://wordpress.org/latest.tar.gz'
          dest: '/tmp/wordpress.tar.gz'
      
      - name: 'Descompacta o wordpress'
        unarchive:
          src: '/tmp/wordpress.tar.gz'
          dest: /var/www/
          remote_src: yes
        become: yes
      
      - name: 'Copiando arquivo de configuração do Wordpress'
        copy:
          src: "{{ wp_installation_dir }}/wp-config-sample.php"
          dest: "{{ wp_installation_dir }}/wp-config.php"
          remote_src: yes
        become: yes

      - name: 'Configura o wp-config com as estradas do banco de dados'
        replace:
          path: "{{ wp_installation_dir }}/wp-config.php"
          regexp: '{{ item.regex }}'
          replace: '{{ item.value }}'
        with_items:
          - { regex:  'database_name_here', value: "{{ wp_db_name }}"}
          - { regex:  'username_here', value: "{{ wp_username }}"}
          - { regex:  'password_here', value: "{{ wp_user_password }}"}
          - { regex:  'localhost', value: "{{ wp_db_ip }}"}
        become: yes
      
      - name: 'Configura o Apache para servir o Wordpress'
        copy:
          src: 'files/000-default.conf'
          dest: '/etc/apache2/sites-available/000-default.conf'
        become: yes
        notify:
          - Reiniciar Apache